services:
  authapi:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: AuthApi/Dockerfile

  CatalogApi:
    image: ${DOCKER_REGISTRY-}CatalogApi
    build:
      context: .
      dockerfile: CatalogApi/Dockerfile
    # depends_on: 'authApi'

