services:
  authapi:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: AuthApi/Dockerfile
    restart: always
    networks:
      - backend-prod

  webapi:
    environment:
      - ASPNETCORE_HTTPS_PORTS=7071
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    restart: always
    networks:
      - backend-prod


networks:
  backend-prod: {}