services:

   identityapi:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/IdentityApi/Dockerfile
    ports:
      - "7000:8081"
    networks:
      - backend-gateway

   catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/CatalogApi/Dockerfile
    ports:
      - "7001:8081"
    networks:
      - backend-gateway


networks:
  backend-gateway: {}