services:
  authapi:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: AuthApi/Dockerfile
    ports:
    - "7000:8080"
    networks:
      - webapi_network

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    # depends_on: 'authApi'


networks:
  webapi_network:
    driver: bridge