services:

   identityapi:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/IdentityApi/Dockerfile
    ports:
      - "7000:80"
    networks:
      - backend-gateway

   catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/CatalogApi/Dockerfile
    ports:
      - "7001:80"
    networks:
      - backend-gateway

   ordersapi:
    image: ${DOCKER_REGISTRY-}ordersapi
    build:
      context: .
      dockerfile: src/OrdersApi/Dockerfile
    ports:
      - "7002:80"
    networks:
      - backend-gateway


networks:
  backend-gateway: {}