name: GitHub Action Demo for a .NET 9 API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build and Test .NET 9 API
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build WebApi Docker image
      run: docker build . --file WebApi/Dockerfile --tag webapi:$(date +%s)

    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - run: dotnet restore ".\AuthApi.Unit.Tests\AuthApi.Unit.Tests.csproj"
    - run: dotnet test ".\AuthApi.Unit.Tests\AuthApi.Unit.Tests.csproj" --no-restore --logger trx --collect:"XPlat Code Coverage" --results-directory ./coverage
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Tests
        path: ./coverage/*.trx
        reporter: dotnet-trx

    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ./coverage/coverage.cobertura.xml
    
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results-AuthApi
        path: TestResults-${{ github.event.repository.updated_at}}
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    - uses: actions/checkout@v4
    - name: Build the Auth Api image
      run: docker build . --file AuthApi/Dockerfile --tag authapi:$(date +%s)
    
