name: GitHub Action Demo for a .NET 9 API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build WebApi Docker image
      run: docker build . --file WebApi/Dockerfile --tag webapi:$(date +%s)

    - uses: actions/checkout@v4
    - name: Build the Auth Api image
      run: docker build . --file AuthApi/Dockerfile --tag authapi:$(date +%s)
    
