name: GitHub Action Demo for a .NET 9 API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build WebApi Docker image
      run: docker build . --file WebApi/Dockerfile --tag webapi:$(date +%s)

    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - run: dotnet restore ".\AuthApi.Unit.Tests\AuthApi.Unit.Tests.csproj"
    - run: dotnet test ".\AuthApi.Unit.Tests\AuthApi.Unit.Tests.csproj" --no-restore --logger trx --results-directory "TestResults-${{ github.event.repository.updated_at}}"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results-AuthApi
        path: TestResults-${{ github.event.repository.updated_at}}
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    - uses: actions/checkout@v4
    - name: Build the Auth Api image
      run: docker build . --file AuthApi/Dockerfile --tag authapi:$(date +%s)
    
